version: "3"

services:
  app:
    build: 
      context: ./
      dockerfile: dev.Dockerfile
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on: 
    - database
  database:
    image: postgres
    container_name: postgres_db
    ports:
    - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data


volumes:
  database: